services:
  postgres:
    image: postgres:15
    container_name: deanery-postgres
    environment:
      POSTGRES_DB: deanery
      POSTGRES_USER: dean
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - deanery-network

  app:
    build: .
    container_name: deanery-app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - deanery-network

volumes:
  postgres_data:

networks:
  deanery-network:
    driver: bridge
